# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): "
    versioning-strategy: lockfile-only
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(deps): "
