name: '🚀 Publish release'
on:
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string
      tag_name:
        required: true
        type: string

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}

      - name: Publish config
        uses: softprops/action-gh-release@v1
        with:
          files: "*.cnfg"
          tag_name: ${{ inputs.tag_name }} 
